# ######################################################################################################################
# Prime Gaming Loot Discord Bot
# ######################################################################################################################

# Token
token: a19fb497cf0c4090b6e19bd82a985c585e0fd8b28a0139ba5783da4a3cf5866b

# ######################################################################################################################
# Twitch Loot
# ######################################################################################################################
twitch:
  # The command to use in chat to display current prime gaming content
  command: "!twitch"

  # Message type
  # - Choose 0 if you want all loot displayed in a single message from the bot
  # - Choose 1 if you want an individual message for each loot (this might spam the chat very quickly)
  message_type: 1

  # List of games to display if there is loot
  games_to_include:
    - Overwatch
    - World of Warcraft
    - Fall Guys

# ######################################################################################################################
# Epic Games
# ######################################################################################################################
epic:
  # The command to use in chat to display current free epic games content
  command: "!epic"

  # Message type
  # - Choose 0 if you want all loot displayed in a single message from the bot
  # - Choose 1 if you want an individual message for each loot (this might spam the chat very quickly)
  message_type: 1
